### ISSUE TITLE
Storage turning off for me in SEM-1.2

### ISSUE THREAD

**Issue by jacquelinedowling** [ClabEnergyProject/SEM-1.2#6]
Hi all,

When I use the following case_input file "case_input_fortyler.csv" and Input_Data folder "Sept2019" I should see PGP and batteries, but they come out as zero in the Output_Data folder. PGP and Batteries are set to non-zero values initially in the case_input file.

Some bug is turning off storage for me in SEM-1.2.

Best,
Jackie

**Comment by d-farnham** [comment]
Hi Jackie,

I believe the model is behaving this way because your input file does not define all of the tech inputs that the model looks for (wind2 and solar2 for example.) It is not yet clear to me why this is  leading the model to neglect some of the defined techs but I am looking into it as this does not seem like desirable behavior to me.

**Comment by jacquelinedowling** [comment]
Hi David,
Awesome, thanks so much for looking into it. I can try running it with wind2 and solar2 set to -1 for example.
Best,
Jackie

**Comment by d-farnham** [comment]
My recommendation would be to work from the "case_input_test_190926.csv" file and change the costs and input files according to your specific case.

**Comment by candisehenry** [comment]
Dave and Jackie- the file that I posted on the slack channel ('case_input.csv', sorry for not using a less generic filename) is altered from the 'case_input_test_190926.csv' file and includes the wind2 and solar2. After doing this I get the issue that Tyler and I were discussing about PGP.

**Comment by d-farnham** [comment]
@candisehenry Do you mind creating a new issue for this (possibly related) unique issue?

**Comment by d-farnham** [comment]
The origin of this issue has been identified. The naming convention for PGP and storage efficiencies changed from "PGP_STORAGE_CHARGING_EFFICIENCY" and "STORAGE_CHARGING_EFFICIENCY", respectively, to "CHARGING_EFFICIENCY_PGP_STORAGE" and "CHARGING_EFFICIENCY_STORAGE" between SEM-1.1 and SEM-1.2.
If you use the SEM-1.1 efficiency naming conventions when running SEM-1.2, then storage is "turned off" and PGP is removed from the system components.
