### ISSUE TITLE
"capacity_solar.value" comes up as empty when PGP is involved

### ISSUE THREAD

**Issue by candisehenry** [ClabEnergyProject/SEM-1.2#7]
When we run SEM 1.2 with PGP turned on (and costs are such that PGP does get built), there is the following error:

> system cost  inf  runtime:  36.50434684753418 seconds
> 
> File "C:\Users\clh19\Documents\Carnegie\SEM\SEM_Code\SEM-1.2-master\Core_Model.py", line 726, in core_model
>    result['CAPACITY_SOLAR'] = np.asscalar(capacity_solar.value)/numerics_demand_scaling
> 
> File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 547, in asscalar
>    return a.item()
> 
> AttributeError: 'NoneType' object has no attribute 'item'

We are using the most updated csv file here (case_input_test_190926.csv which has wind2, solar2, etc.).  If PGP is not part of the mix, then there isn't an issue.

**Comment by candisehenry** [comment]
So far, looking at differences between SEM 1.1 and SEM 1.2 (for code related to PGP), it looks like the differences might be in the Preprocessing_Inputs.py file. There aren't differences in Core_Model.py.

**Comment by d-farnham** [comment]
How do you know that this error is related to PGP penetrating in the system? I am able to run cases where PGP does penetrate and this error does not occur.

**Comment by candisehenry** [comment]
Which technologies are you allowing when PGP penetrates the system? I don't know for certain that this error is related to PGP actually, but all of the scenarios that I ran with PGP gave an error. (Perhaps I did not run the same scenarios as you did.)

**Comment by jacquelinedowling** [comment]
Hi all,

I get the same "CAPACITY_SOLAR" error when I run "case_input_fortyler2.csv".

In this case input file I followed Dave's recommendation and worked from the "case_input_test_190926.csv" file and changed the costs and input files according to my specific case.

Best,
Jackie

**Comment by truggles** [comment]
(sorry I pushed this to master, let's clean these files out after we resolve these)

If we run `case_input_fortyler2.csv` from July 2 to the end of July then there is no problem.  I think part of the problem is that I asked @jacquelinedowling to test this on as much data as possible.  We only have July 2015 to end of 2015 where Shaner's data overlaps with the new demand data.  PGP is subject to the same looping requirements of storage where the first and last hour should be ~ the same storage.  This is VERY difficult for PGP when starting in July and ending in Dec.

Please try running `case_input_fortyler2_short.csv` to test and diff the two to see the only changes are the run start and end dates.

**Comment by truggles** [comment]
With the seasonal aspect of PGP, running over 1 month is kind of safe.  But, 6 months can kill the model

loop defined [here](https://github.com/ClabEnergyProject/SEM-1.2/blob/master/Core_Model.py#L477)

**Comment by truggles** [comment]
Some additional findings:
* it was actually the 1 year case with old demand data which was failing in `case_input_fortyler2.csv`
* only the 1 year case had `unmet` demand turned [off](https://github.com/ClabEnergyProject/SEM-1.2/blob/master/case_input_fortyler2.csv#L156) (scroll to right long ways) forcing 100% reliability
* when turning `unmet` demand on for both cases, both solve.
* the optimal system cost results are similar for both; they differ most in the quantity of PGP storage built as the six month case can not fully take advantage of PGP b/c it lacks a full annual cycle.

Can we close this issue?

**Comment by candisehenry** [comment]
Yes I can confirm that it works fine now with unmet demand turned on so I think we should close this issue.
