### ISSUE TITLE
SEM 1.2 not working for PGP at all

### ISSUE THREAD

**Issue by jacquelinedowling** [ClabEnergyProject/SEM-1.2#9]
Something is wrong such that SEM1.2 is not working for PGP at all. I get the following error below each time. I don't think that this is a gurobi solver convergence problem because the same settings yield good results in SEM1.1. We use the same solver settings and input values in both versions of the model. The model works for a batt+wind+solar case, but it does not work for either pgp+wind+solar, or pgp+batt+wind+solar. Both of these cases were for a full year (2018). Thank you for your help.

result['CAPACITY_SOLAR'] = np.asscalar(capacity_solar.value)/numerics_demand_scaling
  File "/Users/jacquelinedowling/anaconda3/envs/SEM1.2/lib/python3.7/site-packages/numpy/lib/type_check.py", line 547, in asscalar
    return a.item()
AttributeError: 'NoneType' object has no attribute 'item'

**Comment by candisehenry** [comment]
Must start and end year on the same month for PGP to work (or allow for unmet demand).
